#!/usr/bin/env bash

# Date: jeudi 12 février 2015, 12:59:18 (UTC+0100)
# Generated by:
# sh run-generator.sh tcrsig94 'cd4 cd28 tcrlig' 'sre ap1 nfkb nfat sigmab'

# File: tcrsig94.ph
# Inputs: cd4 cd28 tcrlig
# Outputs: sre ap1 nfkb nfat sigmab

ph="tcrsig94.ph"
outputs="sre ap1 nfkb nfat sigmab"
mode=${1}

echo -n "Start time: " && date
echo 'Model: tcrsig94.ph'
echo 'Inputs: cd4 cd28 tcrlig'
echo 'Outputs: sre ap1 nfkb nfat sigmab'

(echo -n "Start time: " && date) >&2
(echo 'Model: tcrsig94.ph') >&2
(echo 'Inputs: cd4 cd28 tcrlig') >&2
(echo 'Outputs: sre ap1 nfkb nfat sigmab') >&2

for cd4 in 0 1; do
for cd28 in 0 1; do
for tcrlig in 0 1; do

init="cd4 $cd4, cd28 $cd28, tcrlig $tcrlig"
echo "--- $init"
for z in $outputs; do
  echo "# $z 1"
  ./unitrun.sh $mode "$cd4$cd28$tcrlig" --no-debug --initial-state "$init" -i $ph $z 1
  [ $? -eq 137 ] && echo '*** Killed ***'
done

done
done
done

echo -n "End time: " && date
(echo -n "End time: " && date) >&2

